### ISSUE TITLE
Not working for AM 6.0.0

### ISSUE THREAD

**Issue by jonasheinisch** [ForgeRock/client-script-auth-tree-node#1]
The plugin cannot be installed with AM v6.0.0.*:

```
ERROR: org.forgerock.openam.auth.nodes.ClientScriptNodePlugin plugin not installed
java.lang.TypeNotPresentException: Type org.forgerock.openam.scripting.ScriptConstants$ScriptContext not present
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:439)
        at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:477)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:347)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
        at java.lang.reflect.Executable.declaredAnnotations(Executable.java:599)
        at java.lang.reflect.Executable.declaredAnnotations(Executable.java:597)
        at java.lang.reflect.Executable.getAnnotation(Executable.java:570)
        at java.lang.reflect.Method.getAnnotation(Method.java:622)
        at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
        at java.lang.reflect.AccessibleObject.isAnnotationPresent(AccessibleObject.java:191)
        at org.forgerock.openam.sm.annotations.AnnotatedServiceMethodUtils.isAttribute(AnnotatedServiceMethodUtils.java:54)
        at java.util.function.Predicate.lambda$or$2(Predicate.java:101)
        at java.util.function.Predicate.lambda$or$2(Predicate.java:101)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
        at org.forgerock.openam.sm.annotations.validators.MethodParameterCountValidator.validate(MethodParameterCountValidator.java:34)
        at org.forgerock.openam.sm.annotations.validators.CompositeValidator.lambda$validate$0(CompositeValidator.java:40)
        at org.forgerock.guava.common.collect.ImmutableList.forEach(ImmutableList.java:407)
        at org.forgerock.openam.sm.annotations.validators.CompositeValidator.validate(CompositeValidator.java:40)
        at org.forgerock.openam.sm.annotations.AnnotatedServiceFactory.createInternal(AnnotatedServiceFactory.java:94)
        at org.forgerock.openam.sm.annotations.AnnotatedServiceFactory.create(AnnotatedServiceFactory.java:89)
        at org.forgerock.openam.sm.SmsAnnotatedServiceRegistry.installService(SmsAnnotatedServiceRegistry.java:156)
        at org.forgerock.openam.plugins.PluginToolsImpl.installAuthNode(PluginToolsImpl.java:137)
        at org.forgerock.openam.auth.node.api.AbstractNodeAmPlugin.onInstall(AbstractNodeAmPlugin.java:45)
        at org.forgerock.openam.plugins.PluginLifecycle.installPlugins(PluginLifecycle.java:119)
        at org.forgerock.openam.plugins.PluginLifecycle.initialise(PluginLifecycle.java:85)
        at com.sun.identity.setup.AMSetupServlet.notifyAmStartup(AMSetupServlet.java:1821)
        at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:217)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.forgerock.openam.scripting.ScriptConstants$ScriptContext
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1309)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1137)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
        ... 55 more
```

That is due to the build is done with am.version=5.5 (cf. pom.xml) and the class ScriptContext cannot be found in version 6.0.0. Any suggestion how to make it work with AM 6.0.0?

**Comment by jonasheinisch** [comment]
Resolved by #2
